code --install-extension 93akkord.output-link-to-file
code --install-extension aaron-bond.better-comments
code --install-extension activecove.marquee
code --install-extension albert.TabOut
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension apvarun.celestial
code --install-extension asvetliakov.vscode-neovim
code --install-extension axetroy.vscode-imagemin
code --install-extension bierner.emojisense
code --install-extension bmuskalla.vscode-tldr
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension burkeholland.simple-react-snippets
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension GraphQL.vscode-graphql
code --install-extension hideoo.toggler
code --install-extension humao.rest-client
code --install-extension IBM.output-colorizer
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension jock.svg
code --install-extension johnpapa.vscode-peacock
code --install-extension jrebocho.vscode-random
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension lamartire.git-indicators
code --install-extension mikestead.dotenv
code --install-extension mkxml.vscode-filesize
code --install-extension Monish.regexsnippets
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natqe.reload
code --install-extension oderwat.indent-rainbow
code --install-extension patbenatar.advanced-new-file
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension prashaantt.node-tdd
code --install-extension qezhu.gitlink
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension RobbOwen.synthwave-vscode
code --install-extension Satoqz.yet-another-discord-presence
code --install-extension spikespaz.vscode-smoothtype
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension TabNine.tabnine-vscode
code --install-extension Tyriar.shell-launcher
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vintharas.learn-vim
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension VSpaceCode.whichkey
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
