#!/bin/sh

# Set session Name
session=`basename $PWD`
sessionEXISTS=$(tmux list-sessions | grep $SESSION)

# Only create tmux session if it doesn't already exist
if [ "$sessionEXISTS" = "" ]
then
    tmux new-session -d -s $session

    tmux rename-window $session
    tmux send-keys -t $session:1 'nvim .' C-m

    tmux new-window -t $session:2  -a -n 'server'
    tmux split-window -h
    tmux select-pane -t 0
    tmux send-keys -t $session 'npm run '

    tmux new-window -t $session:3 -a -n lazygit
    tmux send-keys 'lazygit' C-m

    tmux new-window -t $session:4  -a -n 'git'
    tmux send-keys -t $session 'git fetch --prune --all' C-m

    tmux new-window -t $session:5 -a -n files 'ranger'
    tmux split-window -h
    tmux select-pane -t 0

    tmux new-window -t $session:6 -a -n logs
    tmux split-window -v
    tmux select-pane -t 0

    tmux new-window -t $session:7 -a -n elinks 'elinks -no-connect'
    tmux split-window -h
    tmux select-pane -t 0
    tmux resize-pane -R 30

fi

tmux attach-session -t $session:1
